pub(crate) const COMPONENT_NEAR_ROLE_LIMIT_ACCEPT: &str = "PK/ROLES/SETUP/ROLE-LIMIT/ACCEPT";
pub(crate) const COMPONENT_NEAR_ROLE_LIMIT_DENY: &str = "PK/ROLES/SETUP/ROLE-LIMIT/DENY";
pub(crate) const COMPONENT_LEGACY_ROLE_CLEANUP_ACCEPT: &str = "PK/ROLES/SETUP/LEGACY-ROLES/ACCEPT";
pub(crate) const COMPONENT_LEGACY_ROLE_CLEANUP_DENY: &str = "PK/ROLES/SETUP/LEGACY-ROLES/DENY";

pub(crate) const MODAL_ROLE_SUFFIX_SUBMIT: &str = "PK/ROLES/SETUP/ROLE-SUFFIX/SUBMIT";

pub(crate) const INPUT_ROLE_SUFFIX: &str = "suffix";
